<a href="https://colab.research.google.com/github/sy07/Machine-Learning-with-Python/blob/main/Assignment_Task_4_GoEdu.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Assignment Task-4.  *GO_STP_266*



# Import the numpy package under the name np and Print the numpy version and the configuration

In [1]:
pip install numpy

In [2]:
import numpy as np
np.__version__

'1.19.5'

# Create a null vector of size 10

In [3]:
l=np.zeros(10)
l

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

# Create Simple 1-D array and check type and check data types in array

In [4]:
a=np.array([1,2,3,4])
print(a.dtype)

int64


# How to find number of dimensions, bytes per element and bytes of memory used?

In [5]:
b=np.arange(100)
print("-----arrray---")
print(b)
print("="*50)
print("Dimension of array :",b.ndim)
print("Memory used :",b.itemsize*b.size)

-----arrray---
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
Dimension of array : 1
Memory used : 800


# Create a null vector of size 10 but the fifth value which is 1

In [6]:
a=np.zeros(10)
a[4]=1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


# Create a vector with values ranging from 10 to 49

In [7]:
a=np.arange(10,50)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

# Reverse a vector (first element becomes last)

In [8]:
sorted(a,reverse=True)

[49,
 48,
 47,
 46,
 45,
 44,
 43,
 42,
 41,
 40,
 39,
 38,
 37,
 36,
 35,
 34,
 33,
 32,
 31,
 30,
 29,
 28,
 27,
 26,
 25,
 24,
 23,
 22,
 21,
 20,
 19,
 18,
 17,
 16,
 15,
 14,
 13,
 12,
 11,
 10]

In [9]:
a[:-1]

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

# Create a 3x3 matrix with values ranging from 0 to 8

In [10]:
c=np.arange(0,9).reshape(3,3)
c

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

# Find indices of non-zero elements from [1,2,0,0,4,0]

In [11]:
a1=np.array([1,2,0,0,4,0])
np.nonzero(a1)

(array([0, 1, 4]),)

# Create a 3x3 identity matrix

In [13]:
a2=np.identity(3)
a2

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Create a 3x3x3 array with random values

In [12]:
a3=np.random.random((3,3,3))
a3

array([[[0.03463774, 0.26515704, 0.91618634],
        [0.35023194, 0.77364599, 0.74145753],
        [0.744705  , 0.42601198, 0.99136207]],

       [[0.17703112, 0.93917249, 0.62925798],
        [0.87484497, 0.22223995, 0.31765623],
        [0.63458911, 0.36732271, 0.52347757]],

       [[0.12446756, 0.42447655, 0.93531811],
        [0.08591796, 0.17887603, 0.82752527],
        [0.93884014, 0.44184175, 0.79415063]]])

# Create a 10x10 array with random values and find the minimum and maximum values

In [14]:
a4=np.random.random((10,10))
print(a4)
print("*"*80)
print("maximum in above array : ",a4.max())
print("minimum in above array : ",a4.min())


[[7.77511378e-01 1.88205070e-01 4.49045709e-01 5.12126861e-01
  9.96831727e-01 7.72496787e-01 7.08290654e-01 7.94619127e-01
  6.18510127e-01 7.66691792e-01]
 [3.83981912e-01 1.71609262e-01 3.19210036e-01 2.66840875e-01
  8.68513546e-01 4.93802169e-01 8.84740528e-01 6.14556571e-01
  4.81626552e-01 5.74257720e-02]
 [1.86933120e-01 2.25156368e-01 1.36197637e-01 6.47374414e-02
  9.07260942e-01 4.76980501e-01 4.93750560e-01 8.68220736e-01
  1.54084508e-01 6.09036097e-01]
 [7.51141742e-01 9.64130724e-01 6.30474518e-03 3.15668022e-01
  1.62062343e-01 1.85188322e-01 9.91650937e-01 7.58796342e-01
  8.31200918e-02 4.15972325e-01]
 [4.58398795e-01 9.47261539e-01 1.19273061e-01 4.66656871e-01
  5.61699319e-01 4.98203954e-01 3.90992982e-01 5.72769879e-01
  1.73201290e-01 6.66676179e-01]
 [4.11455025e-01 6.12794673e-01 6.60309117e-01 6.29484146e-01
  5.38021041e-01 7.90181049e-02 1.49153786e-01 8.71308230e-01
  9.48663877e-01 2.64480951e-01]
 [2.34432250e-01 2.63119628e-01 4.53362377e-02 6.54908621e

# Create a random vector of size 30 and find the mean value

In [15]:
a5=np.random.random(10)
print(a5)
print("#"*80)
print("mean of the value of above array is  :",a5.mean())

[0.89941194 0.90242278 0.73549352 0.60057346 0.37206724 0.03871082
 0.90264614 0.06838594 0.13492748 0.16833641]
################################################################################
mean of the value of above array is  : 0.4822975725914775


# Create a 2d array with 1 on the border and 0 inside

In [17]:
#creates a 2d array of 4*4 with all 1's
a6=np.ones((4,4))
#print(a6)

#for row : from 1st row upto last one 
#for column : from 1st column upto last one 
a6[1:-1,1:-1]=0
print(a6)

[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


# How to add a border (filled with 0's) around an existing array?

In [18]:
a6=np.pad(a6, pad_width=1, mode='constant', constant_values=0)
print(a6)

[[0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 0. 0. 1. 0.]
 [0. 1. 0. 0. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0.]]


# How to Accessing/Changing specific elements, rows, columns, etc in Numpy array?
Example - [[ 1 2 3 4 5 6 7] [ 8 9 10 11 12 13 14]]

Get 13, get first row only, get 3rd column only, get [2, 4, 6], replace 13 by 20

In [21]:
a7=np.array([[ 1, 2, 3, 4, 5, 6, 7], [ 8, 9, 10, 11, 12, 13, 14]])
print(a7)
print("1st row : ",a7[0])
print("3rd column : ",a7[:,3])

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
1st row :  [1 2 3 4 5 6 7]
3rd column :  [ 4 11]


# How to Convert a 1D array to a 2D array with 2 rows

In [22]:
a8=np.array([[ 1, 2, 3, 4, 5, 6, 7], [ 8, 9, 10, 11, 12, 13, 14]])
a8.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

# Create the following pattern without hardcoding. Use only numpy functions and the below input array a.

In [23]:
a = np.array([1,2,3])
print(np.r_[(np.repeat(a, 3), np.tile(a, 3))])

[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


# Write a program to show how Numpy taking less memory compared to Python List?

In [24]:
import numpy as np

print("-"*10,"list","-"*10)
l=range(1000)

# this module is used to calculate size
import sys
a=10
print(sys.getsizeof(a)) #memory alocallted to a

#here, one int value takes 28 bytes in a list 
print(sys.getsizeof(a)*len(l))
print("-"*10,"numpy array","-"*10)
a1=np.arange(1000)
print(a1.size)

#to check each item in numpy array 
print(a1.size*a1.itemsize)

---------- list ----------
28
28000
---------- numpy array ----------
1000
8000


# Write a program to show how Numpy taking less time compared to Python List?

In [25]:
import time
import sys

print("-"*10,"list","-"*10)
size = 1000000
l1=range(size)
l2=range(size)

#starting timer
start=time.time()
#2 iterator are taken, inside zip we put both the list, one element from l1 will be put in x and one element from l2 will be put in y
result=[(x+y) for x,y in zip(l1,l2)]
#subtracting the when loop began with after excution of loop
print((time.time()-start)*1000)


print("-"*10,"numpy array","-"*10)
n1=np.arange(size)
n2=np.arange(size)

#starting timer
start=time.time()

result=n1+n2
#subtracting the when loop began with after excution of loop
#time is in micro sec that we mutlipled it to 1000
print((time.time()-start)*1000)

---------- list ----------
125.8540153503418
---------- numpy array ----------
18.025636672973633
